% \VignetteIndexEntry{RAVEL: Removal of Artificial Voxel Effect by Linear Regression}
% \VignettePackage{RAVEL}
% \VignetteDepends{BiocStyle}
% \VignetteEngine{knitr::knitr}

\documentclass[12pt]{article}
\usepackage[numbers]{natbib}
\usepackage{amsthm}
%\newcommand{\minfi}{\Biocpkg{minfi}}

<<style, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\title{RAVEL: Removal of Artificial Voxel Effect by Linear Regression}
\author{Jean-Philippe Fortin, Russell Taki Shinohara}
\begin{document}

\maketitle{}
\setcounter{secnumdepth}{1} 

% Introduction
\section{Introduction}

We use the package \cite{whitestripe:package} for ... 
Work from \cite{ravel}


\section{Creation of a control region}
<<>>=
library(RAVEL)
library(RAVELData)
datadir <- system.file("data",package="RAVELData")
files <- list.files(datadir, pattern="csf_mask.nii.gz", full.names=TRUE)
masks <- pblapply(files, readNIfTI)
control.mask<- mask_intersect(masks)
@


% Reading the data
\section{Reading the data}

<<>>=
files <- list.files(datadir, pattern="processed.nii.gz", full.names=TRUE)
template    <- file.path(datadir, "JHU_MNI_SS_T1.nii.gz")
brain.mask <- file.path(datadir, "JHU_MNI_SS_T1_Brain_Mask.nii.gz")
RAVEL(input.files = files, brain.mask = brain.mask, control.mask = control.mask,WhiteStripe=FALSE)
@



\section*{Session info}

Here is the output of \Rfunction{sessionInfo} on the system on which
this document was compiled:
<<sessionInfo, results="asis", echo=FALSE, eval=TRUE>>=
toLatex(sessionInfo())
@



\bibliography{RAVEL}



\end{document}

